[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html except for specific paths
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Catch all other routes and redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 